FROM openjdk:8u212-jre-alpine3.9

ADD ./target/spring-boot-rest-crud-jpa-posgres-0.0.1-SNAPSHOT.jar /spring-boot-rest-crud-jpa-posgres-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","spring-boot-rest-crud-jpa-posgres-0.0.1-SNAPSHOT.jar"]