--Base de datos sample:  Tablas PRODUCTO CATEGORIA
--============================================================TABLAS-DEMO
CREATE TABLE CATEGORY
(
ID INTEGER PRIMARY KEY NOT NULL ,
NAME VARCHAR (255),
STATE BOOLEAN
);

CREATE TABLE PRODUCT
(
ID INTEGER PRIMARY KEY NOT NULL ,
ID_DEMO_CATEGORY INTEGER, --FK
NAME VARCHAR (255),
PRICE DECIMAL(15,2),
STOCK INTEGER,
CREATE_AT TIMESTAMP,
STATE BOOLEAN,
FOREIGN KEY (ID_DEMO_CATEGORY) REFERENCES CATEGORY (ID)
);

CREATE TABLE USERNAME
(
    USERNAME VARCHAR (255) PRIMARY KEY NOT NULL ,
    PASSWORD VARCHAR (255),
    ROLE VARCHAR (255),
    STATE BOOLEAN
);

--============================================================SECUENCIAS
CREATE SEQUENCE SEQUENCE_CATEGORY;
ALTER TABLE CATEGORY ALTER ID SET DEFAULT NEXTVAL('SEQUENCE_CATEGORY');

CREATE SEQUENCE SEQUENCE_PRODUCT;
ALTER TABLE PRODUCT ALTER ID SET DEFAULT NEXTVAL('SEQUENCE_PRODUCT');

--============================================================DATOS
INSERT INTO CATEGORY ("name", state) VALUES('TECNOLOGIA', true);
INSERT INTO PRODUCT(id_demo_category, "name", price, stock, create_at, state)VALUES (1, 'NOTEBOOK', 1300000, 50, TO_TIMESTAMP('28/06/2022 17:30:00', 'DD/MM/YYYY HH24:MI:SS'), true);
INSERT INTO PRODUCT(id_demo_category, "name", price, stock, create_at, state)VALUES (1, 'MOUSE', 20000, 20, TO_TIMESTAMP('28/06/2022 17:30:00', 'DD/MM/YYYY HH24:MI:SS'), true);

INSERT INTO USERNAME (USERNAME, PASSWORD,ROLE,STATE) VALUES('juan', '$2a$10$WVcYE5QxhVLpN9ViXaATcO6hOJLk9RkQYuuAwxNJfTNXiU37WThUq','CART',true);
INSERT INTO USERNAME (USERNAME, PASSWORD,ROLE,STATE) VALUES('mario', '$2a$10$WVcYE5QxhVLpN9ViXaATcO6hOJLk9RkQYuuAwxNJfTNXiU37WThUq','AUTH',true);