CREATE TABLE PRODUCT
(
    ID INTEGER PRIMARY KEY NOT NULL ,
    NAME VARCHAR (255),
    PRICE DECIMAL(15,2),
    STATE BOOLEAN
);

--============================================================SECUENCIAS
CREATE SEQUENCE SEQUENCE_PRODUCT;
ALTER TABLE PRODUCT ALTER ID SET DEFAULT NEXTVAL('SEQUENCE_PRODUCT');

--============================================================DATOS
INSERT INTO PRODUCT (NAME,PRICE, STATE) VALUES('COMPUTADOR',1300000, true);